"""empty message

Revision ID: 04cf7f8d613d
Revises: 34b34277de9f
Create Date: 2024-01-21 21:17:03.499009

"""
import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "04cf7f8d613d"
down_revision = "34b34277de9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("serialnumber", schema="krecik_iot")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "serialnumber",
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            comment="Row created at",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            comment="Row updated at",
        ),
        sa.PrimaryKeyConstraint("value", name="serialnumber_pkey"),
        schema="krecik_iot",
    )
    # ### end Alembic commands ###
