"""empty message

Revision ID: 1da03a8e88f1
Revises: d261505ab3d8
Create Date: 2024-01-23 16:20:22.577771

"""
import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = "1da03a8e88f1"
down_revision = "d261505ab3d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device", "id", schema="krecik_iot")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('krecik_iot.device_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        schema="krecik_iot",
    )
    # ### end Alembic commands ###
