"""empty message

Revision ID: 6fe925c73763
Revises: 8fb5632cb26c
Create Date: 2024-01-20 17:26:16.582347

"""
import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = "6fe925c73763"
down_revision = "8fb5632cb26c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "serialnumber",
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="Row created at"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, comment="Row updated at"),
        sa.PrimaryKeyConstraint("value"),
        schema="krecik_iot",
    )
    op.add_column("device", sa.Column("serial_number_value", sa.String(), nullable=True), schema="krecik_iot")
    op.add_column("device", sa.Column("key", sa.String(), nullable=True), schema="krecik_iot")
    op.create_foreign_key(
        None,
        "device",
        "serialnumber",
        ["serial_number_value"],
        ["value"],
        source_schema="krecik_iot",
        referent_schema="krecik_iot",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "device", schema="krecik_iot", type_="foreignkey")
    op.drop_column("device", "key", schema="krecik_iot")
    op.drop_column("device", "serial_number_value", schema="krecik_iot")
    op.drop_table("serialnumber", schema="krecik_iot")
    # ### end Alembic commands ###
