"""empty message

Revision ID: 8fb5632cb26c
Revises: 9cb914342651
Create Date: 2024-01-11 19:13:17.566374

"""
import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = "8fb5632cb26c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="Row created at"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, comment="Row updated at"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
        schema="krecik_iot",
    )
    op.create_table(
        "device",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="Row created at"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, comment="Row updated at"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["krecik_iot.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="krecik_iot",
    )
    op.create_table(
        "record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("when", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("pressure", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="Row created at"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, comment="Row updated at"),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["krecik_iot.device.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="krecik_iot",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("record", schema="krecik_iot")
    op.drop_table("device", schema="krecik_iot")
    op.drop_table("user", schema="krecik_iot")
    # ### end Alembic commands ###
