"""empty message

Revision ID: e12cbaeffb7c
Revises: 13d47862d7eb
Create Date: 2023-10-28 16:58:39.420673

"""
import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = "e12cbaeffb7c"
down_revision = "13d47862d7eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("device", sa.Column("name", sa.String(), nullable=False))
    op.alter_column(
        "user",
        "password_hash",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password_hash",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    op.drop_column("device", "name")
    # ### end Alembic commands ###
