"""empty message

Revision ID: ecb86789a826
Revises: ce9aaf51c315
Create Date: 2023-12-28 18:04:04.062490

"""
import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = "ecb86789a826"
down_revision = "ce9aaf51c315"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("device_user_id_fkey", "device", type_="foreignkey")
    op.create_foreign_key(None, "device", "user", ["user_id"], ["id"], source_schema="public", referent_schema="public")
    op.drop_constraint("record_device_id_fkey", "record", type_="foreignkey")
    op.create_foreign_key(
        None, "record", "device", ["device_id"], ["id"], source_schema="public", referent_schema="public"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "record", schema="public", type_="foreignkey")
    op.create_foreign_key("record_device_id_fkey", "record", "device", ["device_id"], ["id"])
    op.drop_constraint(None, "device", schema="public", type_="foreignkey")
    op.create_foreign_key("device_user_id_fkey", "device", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
