"""empty message

Revision ID: f5e0019c1e98
Revises: 04cf7f8d613d
Create Date: 2024-01-21 22:28:42.066070

"""
import sqlalchemy as sa  # noqa: F401
from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision = "f5e0019c1e98"
down_revision = "04cf7f8d613d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activationrequest",
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("encrypted_message", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, comment="Row created at"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, comment="Row updated at"),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["krecik_iot.device.id"],
        ),
        sa.PrimaryKeyConstraint("device_id"),
        schema="krecik_iot",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activationrequest", schema="krecik_iot")
    # ### end Alembic commands ###
